name: Weekly Report
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Update Training Dataset
        run: |
          cd Model_Training && python model.py

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions